// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wnijgbjdogvtyfkjbzkh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InduaWpnYmpkb2d2dHlma2piemtoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwNTA0ODEsImV4cCI6MjA3MzYyNjQ4MX0.RTQrM4So7XVYytvlBUEAvNNbyoZELp-h4tpMDCLqz5w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});